### ISSUE TITLE
Analizar el nombre de los namespace.

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/bifrost-io#25]
En vista de que bifrost pretende ser una solucion de impresión no solo para yures si no tambien para yubiz, yubus , se  debe analizar cambiar el nombre de los namespace en bifrost en uno mas generico

**Comment by OscarDevCPP** [comment]
Se establecio una solución parcial, que para entornos de desarrollo se usara un numero de sucursal distinto
