### ISSUE TITLE
Configurar cors dinamico para express

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/bifrost-io#36]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* La politica de cors de bifrost esta vulnerable

---

## **Describe the solution you'd like**

* Agregar los namespace dinamicos para los servicios de puyu

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by OscarDevCPP** [comment]
Los cors dinamicos tienen que ser manejados por socket.io, y no en express.
Pero socket.io no soporta configurarcion de cors dinamicos
